### ISSUE TITLE
code_editor.py in 3.2.2 - Minimap doesn't catch cursor

### ISSUE THREAD

**Issue by EugeneDudavkin** [K-410/blender-scripts#14]
Hello.
Strange issue in Blender 3.2.2: it refuse to catch cursor on minimap.

In Blender 3.2.1 it work.

**Comment by K-410** [comment]
Hi, thanks for the report!

The script hasn't been updated for years. I'll look into it.

**Comment by K-410** [comment]
I've made some updates. It should now support Blender 3.2.2 release version.

If you still have issues, let me know and I'll reopen this.
