### ISSUE TITLE
Insert 2

### ISSUE THREAD

**Issue by tin2tin** [K-410/blender-scripts#2]
Really, really useful add-on, which imo, should be default behavior in the text editor. 

I don't know if there are cases where you'll need this combination, but in this situation characters are not doubled):

![brackets](https://user-images.githubusercontent.com/1322593/59972330-76594500-958d-11e9-9a63-863ede2f66e9.gif)

In combination with the VSE, we have had a lot of discussion on the topic of inclusion of python operators, and one thing the devs for sure will not include are functions which add additional functionalities to existing operators, because they think it is better to improve the operators in C instead. 

So I guess is that those wonderful(and much needed) improvements of existing functions of yours may have a better chance as (included)add-ons, which needs manual installation, whereas ex. this insert function doesn't exist in Blender now, so it should be included as default behavior - if you ask me. 

[Sorry for all of my ambitions on your behalf. You should do as you like with your work. I'll just happy to encounter your great work here. :-) ]

**Comment by K-410** [comment]
No problem.

The text editor lacks ways of manipulating the caret outside of bpy.ops, which makes it impossible to write behavioral formatting operators on a low level. It's simply unavoidable. I've hoped for something like ``text.caret_line_index`` and ``text.caret_column_index`` to be exposed as props that can be manipulated by addon developers. If something like this was added down the line, the addon code could be simplified a lot.

In any case, I wrote these to aggregate my own usage of the text editor. And if it even remotely helps others to feel more at home in the text editor, then that's just awesome.


As for the behavioral bug, I actually fixed it locally a while ago. I'll update the repo.

**Comment by tin2tin** [comment]
It is a good idea to propose functions to the API which will make add-on writing for the Text Editor more efficient. The big question is how to do it. I do not think many devs are following rightclickselect. 

There is also this: https://devtalk.blender.org/t/blender-python-api-papercuts/6461/16

But the best bet is properly to start a conversation about it here: https://blender.chat/channel/python
Or here: https://blender.chat/channel/blender-coders where the devs hang out. 

It is Campbell who is the owner of the Python API repository: https://wiki.blender.org/wiki/Modules  

Would you like to commit some of your operators for possible inclusion in Blender or as included add-ons - that will for sure help other coders using the Text Editor?
