### ISSUE TITLE
New 2.82 patch changes line to code distance and breaks add-ons

### ISSUE THREAD

**Issue by tin2tin** [K-410/blender-scripts#5]
Unfortunately a side effect of this patch breaks the add-ons with drawing code because it changes the distance between line numbers and code(ex in Code Editor are the white-space and indentation helpers positioned off): https://developer.blender.org/D6268

**Comment by K-410** [comment]
Thanks for the heads-up. Will look into it!

**Comment by tin2tin** [comment]
Thank you!
